ANCHOR_ITEM_ID: 264
DEFAULT_NUMBER_IN_MARKET: 100
SELLING_TAX_RATE: 0.07
BUYING_TAX_RATE: 0.03
YOU_SELL_ITEM_TEXT: 'ยงa[??ๆ?ๅ?ๅด]ยง7 : ไฝ่ณฃ?บ %id%:%data% * %sold_number% ไธ??ฑ่ณบไ?? : ยง6%total_price%ยง7.
  ๅธๅดไธๅฉ้ค? %item_left% ??'
YOU_BUY_ITEM_TEXT: 'ยงa[??ๆ?ๅ?ๅด]ยง7 : ไฝ่ณผ่ฒ? %id%:%data% * %sold_number% ไธ??ฑ?ฑไบ? : ยง6%total_price%ยง7.
  ๅธๅดไธๅฉ้ค? %item_left% ??'
NO_ITEM_LEFT: 'ยงa[??ๆ?ๅ?ๅด]ยง7 : %id%:%data% ?จๅธๅดไธๅฉ้ค? %item_left% ??'
YOU_NOW_HAVE: 'ยงa[??ๆ?ๅ?ๅด]ยง7 : ไฝ็พ?จ??้?้ข $%balance%.'
